export const ROUTES={
    LANDING: "/",
    LOGIN: "/login",
    SIGNUP: "/signup",
    DASHBOARD: "/dashboard",
    FORECAST: "/dashboard/forecast",
    MENU_ANALYTICS: "/dashboard/menu-analytics",
    WASTE: "/dashboard/waste",
    REVENUE: "/dashboard/revenue",
    INSIGHTS: "/dashboard/insights",
    MENU: "/dashboard/menu",
    STAFF: "/dashboard/staff",
    INVENTORY: "/dashboard/inventory",
    FEEDBACK: "/dashboard/feedback",
    REPORTS: "/dashboard/reports",
    SETTINGS: "/dashboard/settings",
    RESTAURANTS: "/dashboard/restaurants",
    USERS: "/dashboard/users",
    PLATFORM_ANALYTICS: "/dashboard/platform-analytics",
    PLATFORM_SETTINGS: "/dashboard/platform-settings",
    PROFILE: "/dashboard/profile",
    BILLING: "/dashboard/billing",
    NOT_FOUND: "*"
}
