name: Sync to Hugging Face Space
on:
  push:
    branches:
      - feature/model-v2 # 🔴 CHANGE THIS to your specific branch name if it's not 'main'

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://Youseef-Awaad:$HF_TOKEN@huggingface.co/spaces/Youseef-Awaad/ZeroBite-ai-engine
          git push --force space HEAD:main
